name: Notion to Obsidian Conversion

on:
  push:
    paths:
      - 'content/*.md'  # Trigger on changes to markdown files in the 'content/' directory
  workflow_dispatch:   # Allow manual trigger via GitHub Actions UI

jobs:
  convert_notion_to_obsidian:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'   # You can specify the Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies if you have any

    - name: Get modified markdown files
      run: |
        # Ensure the repository is up to date with all commits
        git fetch --prune --unshallow

        # List the changed markdown files in the commit
        echo "Modified Markdown files:"
        git diff --name-only $GITHUB_SHA $GITHUB_BASE_REF | grep '^content/.*\.md$' > changed_files.txt

        # If no markdown files have been changed, exit early
        if [ ! -s changed_files.txt ]; then
          echo "No markdown files changed. Skipping conversion."
          exit 0
        fi

        cat changed_files.txt

    - name: Process each modified file
      run: |
        # Read each file from the list and process it with the Python script
        while IFS= read -r file; do
          echo "Processing file: $file"
          python scripts/convert_notion_to_obsidian.py "$file"
        done < changed_files.txt

    - name: Commit and push changes (if any)
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add content/*.md  # Add all modified markdown files
        git commit -m 'Update converted content from Notion to Obsidian format'
        git push
      continue-on-error: true  # Ignore errors if no changes are made to the files
